// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ (interfaces: AccountTypeRepository)
//
// Generated by this command:
//
//	mockgen ./internal/domain/ AccountTypeRepository
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	db "github.com/Edu58/Oplan/internal/database/sqlc"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountTypeRepository is a mock of AccountTypeRepository interface.
type MockAccountTypeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountTypeRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountTypeRepositoryMockRecorder is the mock recorder for MockAccountTypeRepository.
type MockAccountTypeRepositoryMockRecorder struct {
	mock *MockAccountTypeRepository
}

// NewMockAccountTypeRepository creates a new mock instance.
func NewMockAccountTypeRepository(ctrl *gomock.Controller) *MockAccountTypeRepository {
	mock := &MockAccountTypeRepository{ctrl: ctrl}
	mock.recorder = &MockAccountTypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountTypeRepository) EXPECT() *MockAccountTypeRepositoryMockRecorder {
	return m.recorder
}

// CreateAccountType mocks base method.
func (m *MockAccountTypeRepository) CreateAccountType(ctx context.Context, arg db.CreateAccountTypeParams) (*db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccountType", ctx, arg)
	ret0, _ := ret[0].(*db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccountType indicates an expected call of CreateAccountType.
func (mr *MockAccountTypeRepositoryMockRecorder) CreateAccountType(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccountType", reflect.TypeOf((*MockAccountTypeRepository)(nil).CreateAccountType), ctx, arg)
}

// DeleteAccountType mocks base method.
func (m *MockAccountTypeRepository) DeleteAccountType(ctx context.Context, id pgtype.UUID) (*db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccountType", ctx, id)
	ret0, _ := ret[0].(*db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccountType indicates an expected call of DeleteAccountType.
func (mr *MockAccountTypeRepositoryMockRecorder) DeleteAccountType(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccountType", reflect.TypeOf((*MockAccountTypeRepository)(nil).DeleteAccountType), ctx, id)
}

// GetAccountTypeById mocks base method.
func (m *MockAccountTypeRepository) GetAccountTypeById(ctx context.Context, id pgtype.UUID) (*db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountTypeById", ctx, id)
	ret0, _ := ret[0].(*db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountTypeById indicates an expected call of GetAccountTypeById.
func (mr *MockAccountTypeRepositoryMockRecorder) GetAccountTypeById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountTypeById", reflect.TypeOf((*MockAccountTypeRepository)(nil).GetAccountTypeById), ctx, id)
}

// GetAccountTypeByName mocks base method.
func (m *MockAccountTypeRepository) GetAccountTypeByName(ctx context.Context, name string) (*db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountTypeByName", ctx, name)
	ret0, _ := ret[0].(*db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountTypeByName indicates an expected call of GetAccountTypeByName.
func (mr *MockAccountTypeRepositoryMockRecorder) GetAccountTypeByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountTypeByName", reflect.TypeOf((*MockAccountTypeRepository)(nil).GetAccountTypeByName), ctx, name)
}

// ListAccountTypes mocks base method.
func (m *MockAccountTypeRepository) ListAccountTypes(ctx context.Context) ([]*db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountTypes", ctx)
	ret0, _ := ret[0].([]*db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccountTypes indicates an expected call of ListAccountTypes.
func (mr *MockAccountTypeRepositoryMockRecorder) ListAccountTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountTypes", reflect.TypeOf((*MockAccountTypeRepository)(nil).ListAccountTypes), ctx)
}

// UpdateAccountTypeByID mocks base method.
func (m *MockAccountTypeRepository) UpdateAccountTypeByID(ctx context.Context, arg db.UpdateAccountTypeByIDParams) (*db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountTypeByID", ctx, arg)
	ret0, _ := ret[0].(*db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccountTypeByID indicates an expected call of UpdateAccountTypeByID.
func (mr *MockAccountTypeRepositoryMockRecorder) UpdateAccountTypeByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountTypeByID", reflect.TypeOf((*MockAccountTypeRepository)(nil).UpdateAccountTypeByID), ctx, arg)
}
