// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ (interfaces: AccountTypeRepository)
//
// Generated by this command:
//
//	mockgen ./internal/domain/ AccountTypeRepository
//

// Package mock_repo is a generated GoMock package.
package mock_repo

import (
	context "context"
	reflect "reflect"

	domain "github.com/Edu58/Oplan/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountTypeRepository is a mock of AccountTypeRepository interface.
type MockAccountTypeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountTypeRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountTypeRepositoryMockRecorder is the mock recorder for MockAccountTypeRepository.
type MockAccountTypeRepositoryMockRecorder struct {
	mock *MockAccountTypeRepository
}

// NewMockAccountTypeRepository creates a new mock instance.
func NewMockAccountTypeRepository(ctrl *gomock.Controller) *MockAccountTypeRepository {
	mock := &MockAccountTypeRepository{ctrl: ctrl}
	mock.recorder = &MockAccountTypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountTypeRepository) EXPECT() *MockAccountTypeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAccountTypeRepository) Create(ctx context.Context, req domain.CreateAccountTypeParams) (*domain.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*domain.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccountTypeRepositoryMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountTypeRepository)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockAccountTypeRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAccountTypeRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAccountTypeRepository)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockAccountTypeRepository) Exists(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockAccountTypeRepositoryMockRecorder) Exists(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockAccountTypeRepository)(nil).Exists), ctx, name)
}

// GetByID mocks base method.
func (m *MockAccountTypeRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAccountTypeRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAccountTypeRepository)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockAccountTypeRepository) GetByName(ctx context.Context, name string) (*domain.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*domain.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockAccountTypeRepositoryMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockAccountTypeRepository)(nil).GetByName), ctx, name)
}

// List mocks base method.
func (m *MockAccountTypeRepository) List(ctx context.Context) ([]*domain.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAccountTypeRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAccountTypeRepository)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockAccountTypeRepository) Update(ctx context.Context, req domain.UpdateAccountTypeByIDParams) (*domain.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(*domain.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAccountTypeRepositoryMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccountTypeRepository)(nil).Update), ctx, req)
}
