// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ (interfaces: AccountTypeService)
//
// Generated by this command:
//
//	mockgen ./internal/domain/ AccountTypeService
//

// Package mock_domain is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	domain "github.com/Edu58/Oplan/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountTypeService is a mock of AccountTypeService interface.
type MockAccountTypeService struct {
	ctrl     *gomock.Controller
	recorder *MockAccountTypeServiceMockRecorder
	isgomock struct{}
}

// MockAccountTypeServiceMockRecorder is the mock recorder for MockAccountTypeService.
type MockAccountTypeServiceMockRecorder struct {
	mock *MockAccountTypeService
}

// NewMockAccountTypeService creates a new mock instance.
func NewMockAccountTypeService(ctrl *gomock.Controller) *MockAccountTypeService {
	mock := &MockAccountTypeService{ctrl: ctrl}
	mock.recorder = &MockAccountTypeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountTypeService) EXPECT() *MockAccountTypeServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAccountTypeService) Create(ctx context.Context, req domain.CreateAccountTypeParams) (*domain.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*domain.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccountTypeServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountTypeService)(nil).Create), ctx, req)
}

// ListAll mocks base method.
func (m *MockAccountTypeService) ListAll(ctx context.Context) ([]*domain.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]*domain.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockAccountTypeServiceMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockAccountTypeService)(nil).ListAll), ctx)
}
