// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ (interfaces: AccountTypeService)
//
// Generated by this command:
//
//	mockgen ./internal/domain/ AccountTypeService
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	db "github.com/Edu58/Oplan/internal/database/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountTypeService is a mock of AccountTypeService interface.
type MockAccountTypeService struct {
	ctrl     *gomock.Controller
	recorder *MockAccountTypeServiceMockRecorder
	isgomock struct{}
}

// MockAccountTypeServiceMockRecorder is the mock recorder for MockAccountTypeService.
type MockAccountTypeServiceMockRecorder struct {
	mock *MockAccountTypeService
}

// NewMockAccountTypeService creates a new mock instance.
func NewMockAccountTypeService(ctrl *gomock.Controller) *MockAccountTypeService {
	mock := &MockAccountTypeService{ctrl: ctrl}
	mock.recorder = &MockAccountTypeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountTypeService) EXPECT() *MockAccountTypeServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAccountTypeService) Create(ctx context.Context, arg db.CreateAccountTypeParams) (*db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg)
	ret0, _ := ret[0].(*db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccountTypeServiceMockRecorder) Create(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountTypeService)(nil).Create), ctx, arg)
}

// List mocks base method.
func (m *MockAccountTypeService) List(ctx context.Context) ([]*db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAccountTypeServiceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAccountTypeService)(nil).List), ctx)
}
