// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    name,
    from_time,
    to_time,
    capacity,
    policies_and_rules,
    min_age,
    max_age,
    age_restriction,
    public,
    require_ticket,
    event_type_id,
    inserted_at,
    updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, name, description, from_time, to_time, capacity, policies_and_rules, min_age, max_age, age_restriction, public, require_ticket, event_type_id, inserted_at, updated_at
`

type CreateEventParams struct {
	Name             string     `json:"name"`
	FromTime         time.Time  `json:"from_time"`
	ToTime           time.Time  `json:"to_time"`
	Capacity         int32      `json:"capacity"`
	PoliciesAndRules *string    `json:"policies_and_rules"`
	MinAge           int32      `json:"min_age"`
	MaxAge           *int32     `json:"max_age"`
	AgeRestriction   *bool      `json:"age_restriction"`
	Public           *bool      `json:"public"`
	RequireTicket    *bool      `json:"require_ticket"`
	EventTypeID      uuid.UUID  `json:"event_type_id"`
	InsertedAt       *time.Time `json:"inserted_at"`
	UpdatedAt        *time.Time `json:"updated_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Name,
		arg.FromTime,
		arg.ToTime,
		arg.Capacity,
		arg.PoliciesAndRules,
		arg.MinAge,
		arg.MaxAge,
		arg.AgeRestriction,
		arg.Public,
		arg.RequireTicket,
		arg.EventTypeID,
		arg.InsertedAt,
		arg.UpdatedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.FromTime,
		&i.ToTime,
		&i.Capacity,
		&i.PoliciesAndRules,
		&i.MinAge,
		&i.MaxAge,
		&i.AgeRestriction,
		&i.Public,
		&i.RequireTicket,
		&i.EventTypeID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEventById = `-- name: DeleteEventById :exec
DELETE FROM events
WHERE id = $1
`

func (q *Queries) DeleteEventById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventById, id)
	return err
}

const getEventById = `-- name: GetEventById :one
SELECT id, name, description, from_time, to_time, capacity, policies_and_rules, min_age, max_age, age_restriction, public, require_ticket, event_type_id, inserted_at, updated_at FROM events
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetEventById(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventById, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.FromTime,
		&i.ToTime,
		&i.Capacity,
		&i.PoliciesAndRules,
		&i.MinAge,
		&i.MaxAge,
		&i.AgeRestriction,
		&i.Public,
		&i.RequireTicket,
		&i.EventTypeID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByName = `-- name: GetEventByName :one
SELECT id, name, description, from_time, to_time, capacity, policies_and_rules, min_age, max_age, age_restriction, public, require_ticket, event_type_id, inserted_at, updated_at FROM events
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetEventByName(ctx context.Context, name string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByName, name)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.FromTime,
		&i.ToTime,
		&i.Capacity,
		&i.PoliciesAndRules,
		&i.MinAge,
		&i.MaxAge,
		&i.AgeRestriction,
		&i.Public,
		&i.RequireTicket,
		&i.EventTypeID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT events.id, events.name, events.description, events.from_time, events.to_time, events.capacity, events.policies_and_rules, events.min_age, events.max_age, events.age_restriction, events.public, events.require_ticket, events.event_type_id, events.inserted_at, events.updated_at, event_types.id, event_types.name, event_types.description, event_types.active, event_types.inserted_at, event_types.updated_at FROM events
JOIN event_types ON event_types.id = events.event_type_id
LIMIT $1 OFFSET $2
`

type ListEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListEventsRow struct {
	ID               uuid.UUID  `json:"id"`
	Name             string     `json:"name"`
	Description      *string    `json:"description"`
	FromTime         time.Time  `json:"from_time"`
	ToTime           time.Time  `json:"to_time"`
	Capacity         int32      `json:"capacity"`
	PoliciesAndRules *string    `json:"policies_and_rules"`
	MinAge           int32      `json:"min_age"`
	MaxAge           *int32     `json:"max_age"`
	AgeRestriction   *bool      `json:"age_restriction"`
	Public           *bool      `json:"public"`
	RequireTicket    *bool      `json:"require_ticket"`
	EventTypeID      uuid.UUID  `json:"event_type_id"`
	InsertedAt       *time.Time `json:"inserted_at"`
	UpdatedAt        *time.Time `json:"updated_at"`
	EventType        EventType  `json:"event_type"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.FromTime,
			&i.ToTime,
			&i.Capacity,
			&i.PoliciesAndRules,
			&i.MinAge,
			&i.MaxAge,
			&i.AgeRestriction,
			&i.Public,
			&i.RequireTicket,
			&i.EventTypeID,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.EventType.ID,
			&i.EventType.Name,
			&i.EventType.Description,
			&i.EventType.Active,
			&i.EventType.InsertedAt,
			&i.EventType.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventById = `-- name: UpdateEventById :one
UPDATE events
SET
name = $2,
from_time = $3,
to_time = $4,
capacity = $5,
policies_and_rules = $6,
min_age = $7,
max_age = $8,
age_restriction = $9,
public = $10,
require_ticket = $11,
event_type_id = $11
WHERE id = $1
RETURNING id, name, description, from_time, to_time, capacity, policies_and_rules, min_age, max_age, age_restriction, public, require_ticket, event_type_id, inserted_at, updated_at
`

type UpdateEventByIdParams struct {
	ID               uuid.UUID `json:"id"`
	Name             string    `json:"name"`
	FromTime         time.Time `json:"from_time"`
	ToTime           time.Time `json:"to_time"`
	Capacity         int32     `json:"capacity"`
	PoliciesAndRules *string   `json:"policies_and_rules"`
	MinAge           int32     `json:"min_age"`
	MaxAge           *int32    `json:"max_age"`
	AgeRestriction   *bool     `json:"age_restriction"`
	Public           *bool     `json:"public"`
	RequireTicket    *bool     `json:"require_ticket"`
}

func (q *Queries) UpdateEventById(ctx context.Context, arg UpdateEventByIdParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEventById,
		arg.ID,
		arg.Name,
		arg.FromTime,
		arg.ToTime,
		arg.Capacity,
		arg.PoliciesAndRules,
		arg.MinAge,
		arg.MaxAge,
		arg.AgeRestriction,
		arg.Public,
		arg.RequireTicket,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.FromTime,
		&i.ToTime,
		&i.Capacity,
		&i.PoliciesAndRules,
		&i.MinAge,
		&i.MaxAge,
		&i.AgeRestriction,
		&i.Public,
		&i.RequireTicket,
		&i.EventTypeID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}
