// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_types.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createEventType = `-- name: CreateEventType :one
INSERT INTO event_types (
    name,
    description,
    active
) VALUES (
  $1, $2, $3
) RETURNING id, name, description, active, inserted_at, updated_at
`

type CreateEventTypeParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Active      bool    `json:"active"`
}

func (q *Queries) CreateEventType(ctx context.Context, arg CreateEventTypeParams) (EventType, error) {
	row := q.db.QueryRow(ctx, createEventType, arg.Name, arg.Description, arg.Active)
	var i EventType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEventType = `-- name: DeleteEventType :exec
DELETE FROM event_types
WHERE id = $1
`

func (q *Queries) DeleteEventType(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventType, id)
	return err
}

const getEventTypeById = `-- name: GetEventTypeById :one
SELECT id, name, description, active, inserted_at, updated_at FROM event_types
WHERE id = $1
AND active
LIMIT 1
`

func (q *Queries) GetEventTypeById(ctx context.Context, id uuid.UUID) (EventType, error) {
	row := q.db.QueryRow(ctx, getEventTypeById, id)
	var i EventType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventTypeByName = `-- name: GetEventTypeByName :one
SELECT id, name, description, active, inserted_at, updated_at FROM event_types
WHERE name = $1
AND active
LIMIT 1
`

func (q *Queries) GetEventTypeByName(ctx context.Context, name string) (EventType, error) {
	row := q.db.QueryRow(ctx, getEventTypeByName, name)
	var i EventType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventTypes = `-- name: ListEventTypes :many
SELECT id, name, description, active, inserted_at, updated_at FROM event_types
WHERE active
`

func (q *Queries) ListEventTypes(ctx context.Context) ([]EventType, error) {
	rows, err := q.db.Query(ctx, listEventTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventType{}
	for rows.Next() {
		var i EventType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Active,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventTypeById = `-- name: UpdateEventTypeById :one
UPDATE event_types
SET
  name = $2,
  description = $3
WHERE id = $1
RETURNING id, name, description, active, inserted_at, updated_at
`

type UpdateEventTypeByIdParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

func (q *Queries) UpdateEventTypeById(ctx context.Context, arg UpdateEventTypeByIdParams) (EventType, error) {
	row := q.db.QueryRow(ctx, updateEventTypeById, arg.ID, arg.Name, arg.Description)
	var i EventType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}
