// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountType struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Active     pgtype.Bool        `json:"active"`
	InsertedAt pgtype.Timestamptz `json:"inserted_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	Username       string             `json:"username"`
	FirstName      string             `json:"first_name"`
	LastName       pgtype.Text        `json:"last_name"`
	Password       string             `json:"password"`
	Msisdn         pgtype.Text        `json:"msisdn"`
	Dob            pgtype.Date        `json:"dob"`
	EmailVerified  pgtype.Bool        `json:"email_verified"`
	MsisdnVerified pgtype.Bool        `json:"msisdn_verified"`
	Active         pgtype.Bool        `json:"active"`
	AccountTypeID  pgtype.UUID        `json:"account_type_id"`
	InsertedAt     pgtype.Timestamptz `json:"inserted_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
