// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otp_store.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOTP = `-- name: CreateOTP :one
INSERT INTO otp_store (id,
                       identifier,
                       value,
                       expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (identifier)
    DO UPDATE SET value      = EXCLUDED.value,
                  expires_at = EXCLUDED.expires_at
RETURNING id, identifier, value, expires_at
`

type CreateOTPParams struct {
	ID         uuid.UUID  `json:"id"`
	Identifier string     `json:"identifier"`
	Value      string     `json:"value"`
	ExpiresAt  *time.Time `json:"expires_at"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpStore, error) {
	row := q.db.QueryRow(ctx, createOTP,
		arg.ID,
		arg.Identifier,
		arg.Value,
		arg.ExpiresAt,
	)
	var i OtpStore
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Value,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteOTP = `-- name: DeleteOTP :exec
DELETE
FROM otp_store
WHERE identifier = $1
`

func (q *Queries) DeleteOTP(ctx context.Context, identifier string) error {
	_, err := q.db.Exec(ctx, deleteOTP, identifier)
	return err
}

const getOTP = `-- name: GetOTP :one
SELECT id, identifier, value, expires_at
FROM otp_store
WHERE identifier = $1
LIMIT 1
`

func (q *Queries) GetOTP(ctx context.Context, identifier string) (OtpStore, error) {
	row := q.db.QueryRow(ctx, getOTP, identifier)
	var i OtpStore
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Value,
		&i.ExpiresAt,
	)
	return i, err
}

const updateOTP = `-- name: UpdateOTP :one
UPDATE otp_store
SET value     = $2,
    expires_at=$3
WHERE identifier = $1
RETURNING id, identifier, value, expires_at
`

type UpdateOTPParams struct {
	Identifier string     `json:"identifier"`
	Value      string     `json:"value"`
	ExpiresAt  *time.Time `json:"expires_at"`
}

func (q *Queries) UpdateOTP(ctx context.Context, arg UpdateOTPParams) (OtpStore, error) {
	row := q.db.QueryRow(ctx, updateOTP, arg.Identifier, arg.Value, arg.ExpiresAt)
	var i OtpStore
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Value,
		&i.ExpiresAt,
	)
	return i, err
}
