// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSession(ctx context.Context, sessionID string) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetSessionBySessionId(ctx context.Context, sessionID string) (Session, error)
	GetSessionByUserId(ctx context.Context, userID uuid.UUID) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailForUpdate(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByIdForUpdate(ctx context.Context, id uuid.UUID) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateSessionIsBlocked(ctx context.Context, arg UpdateSessionIsBlockedParams) (Session, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
}

var _ Querier = (*Queries)(nil)
