// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id,
    session_id,
    client_ip,
    is_blocked,
    expires_at
) VALUES (
  $1, $2, $3, $4, $5
) ON CONFLICT (user_id, session_id)
    DO UPDATE SET session_id = EXCLUDED.session_id,
                  expires_at = EXCLUDED.expires_at
  RETURNING user_id, session_id, client_ip, is_blocked, expires_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID  `json:"user_id"`
	SessionID uuid.UUID  `json:"session_id"`
	ClientIp  *string    `json:"client_ip"`
	IsBlocked bool       `json:"is_blocked"`
	ExpiresAt *time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.SessionID,
		arg.ClientIp,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.UserID,
		&i.SessionID,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE session_id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, sessionID)
	return err
}

const getSessionBySessionId = `-- name: GetSessionBySessionId :one
SELECT user_id, session_id, client_ip, is_blocked, expires_at FROM sessions
WHERE session_id = $1 LIMIT 1
`

func (q *Queries) GetSessionBySessionId(ctx context.Context, sessionID uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionBySessionId, sessionID)
	var i Session
	err := row.Scan(
		&i.UserID,
		&i.SessionID,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
	)
	return i, err
}

const getSessionByUserId = `-- name: GetSessionByUserId :one
SELECT user_id, session_id, client_ip, is_blocked, expires_at FROM sessions
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetSessionByUserId(ctx context.Context, userID uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByUserId, userID)
	var i Session
	err := row.Scan(
		&i.UserID,
		&i.SessionID,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
	)
	return i, err
}

const getSessionWithUserBySessionId = `-- name: GetSessionWithUserBySessionId :one
SELECT sessions.user_id, sessions.session_id, sessions.client_ip, sessions.is_blocked, sessions.expires_at, users.id, users.email, users.first_name, users.last_name, users.password, users.msisdn, users.email_verified, users.msisdn_verified, users.active, users.inserted_at, users.updated_at FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE session_id = $1 LIMIT 1
`

type GetSessionWithUserBySessionIdRow struct {
	UserID    uuid.UUID  `json:"user_id"`
	SessionID uuid.UUID  `json:"session_id"`
	ClientIp  *string    `json:"client_ip"`
	IsBlocked bool       `json:"is_blocked"`
	ExpiresAt *time.Time `json:"expires_at"`
	User      User       `json:"user"`
}

func (q *Queries) GetSessionWithUserBySessionId(ctx context.Context, sessionID uuid.UUID) (GetSessionWithUserBySessionIdRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUserBySessionId, sessionID)
	var i GetSessionWithUserBySessionIdRow
	err := row.Scan(
		&i.UserID,
		&i.SessionID,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.Password,
		&i.User.Msisdn,
		&i.User.EmailVerified,
		&i.User.MsisdnVerified,
		&i.User.Active,
		&i.User.InsertedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const updateSessionIsBlocked = `-- name: UpdateSessionIsBlocked :one
UPDATE sessions
SET
  is_blocked = $2
WHERE session_id = $1
RETURNING user_id, session_id, client_ip, is_blocked, expires_at
`

type UpdateSessionIsBlockedParams struct {
	SessionID uuid.UUID `json:"session_id"`
	IsBlocked bool      `json:"is_blocked"`
}

func (q *Queries) UpdateSessionIsBlocked(ctx context.Context, arg UpdateSessionIsBlockedParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionIsBlocked, arg.SessionID, arg.IsBlocked)
	var i Session
	err := row.Scan(
		&i.UserID,
		&i.SessionID,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
	)
	return i, err
}
