// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
email,
first_name,
last_name,
password,
msisdn,
email_verified,
msisdn_verified,
active
) VALUES (
$1, 
$2, 
$3, 
$4, 
$5, 
$6, 
$7, 
$8
) RETURNING id, email, first_name, last_name, password, msisdn, email_verified, msisdn_verified, active, inserted_at, updated_at
`

type CreateUserParams struct {
	Email          string  `json:"email"`
	FirstName      string  `json:"first_name"`
	LastName       *string `json:"last_name"`
	Password       string  `json:"password"`
	Msisdn         *string `json:"msisdn"`
	EmailVerified  *bool   `json:"email_verified"`
	MsisdnVerified *bool   `json:"msisdn_verified"`
	Active         *bool   `json:"active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Password,
		arg.Msisdn,
		arg.EmailVerified,
		arg.MsisdnVerified,
		arg.Active,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Password,
		&i.Msisdn,
		&i.EmailVerified,
		&i.MsisdnVerified,
		&i.Active,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, first_name, last_name, password, msisdn, email_verified, msisdn_verified, active, inserted_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Password,
		&i.Msisdn,
		&i.EmailVerified,
		&i.MsisdnVerified,
		&i.Active,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailForUpdate = `-- name: GetUserByEmailForUpdate :one
SELECT id, email, first_name, last_name, password, msisdn, email_verified, msisdn_verified, active, inserted_at, updated_at FROM users
WHERE email = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetUserByEmailForUpdate(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailForUpdate, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Password,
		&i.Msisdn,
		&i.EmailVerified,
		&i.MsisdnVerified,
		&i.Active,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, first_name, last_name, password, msisdn, email_verified, msisdn_verified, active, inserted_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Password,
		&i.Msisdn,
		&i.EmailVerified,
		&i.MsisdnVerified,
		&i.Active,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIdForUpdate = `-- name: GetUserByIdForUpdate :one
SELECT id, email, first_name, last_name, password, msisdn, email_verified, msisdn_verified, active, inserted_at, updated_at FROM users
WHERE id = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetUserByIdForUpdate(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Password,
		&i.Msisdn,
		&i.EmailVerified,
		&i.MsisdnVerified,
		&i.Active,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, first_name, last_name, password, msisdn, email_verified, msisdn_verified, active, inserted_at, updated_at FROM users
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Password,
			&i.Msisdn,
			&i.EmailVerified,
			&i.MsisdnVerified,
			&i.Active,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users
SET email = $2
WHERE id = $1
RETURNING id, email, first_name, last_name, password, msisdn, email_verified, msisdn_verified, active, inserted_at, updated_at
`

type UpdateUserEmailParams struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Password,
		&i.Msisdn,
		&i.EmailVerified,
		&i.MsisdnVerified,
		&i.Active,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}
