// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/database/sqlc/ (interfaces: Store)
//
// Generated by this command:
//
//	mockgen ./internal/database/sqlc/ Store
//

// Package mock_db is a generated GoMock package.
package mock_db

import (
	context "context"
	reflect "reflect"

	db "github.com/Edu58/Oplan/internal/database/sqlc"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateAccountType mocks base method.
func (m *MockStore) CreateAccountType(ctx context.Context, arg db.CreateAccountTypeParams) (db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccountType", ctx, arg)
	ret0, _ := ret[0].(db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccountType indicates an expected call of CreateAccountType.
func (mr *MockStoreMockRecorder) CreateAccountType(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccountType", reflect.TypeOf((*MockStore)(nil).CreateAccountType), ctx, arg)
}

// DeleteAccountType mocks base method.
func (m *MockStore) DeleteAccountType(ctx context.Context, id pgtype.UUID) (db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccountType", ctx, id)
	ret0, _ := ret[0].(db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccountType indicates an expected call of DeleteAccountType.
func (mr *MockStoreMockRecorder) DeleteAccountType(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccountType", reflect.TypeOf((*MockStore)(nil).DeleteAccountType), ctx, id)
}

// GetAccountTypeById mocks base method.
func (m *MockStore) GetAccountTypeById(ctx context.Context, id pgtype.UUID) (db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountTypeById", ctx, id)
	ret0, _ := ret[0].(db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountTypeById indicates an expected call of GetAccountTypeById.
func (mr *MockStoreMockRecorder) GetAccountTypeById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountTypeById", reflect.TypeOf((*MockStore)(nil).GetAccountTypeById), ctx, id)
}

// GetAccountTypeByName mocks base method.
func (m *MockStore) GetAccountTypeByName(ctx context.Context, name string) (db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountTypeByName", ctx, name)
	ret0, _ := ret[0].(db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountTypeByName indicates an expected call of GetAccountTypeByName.
func (mr *MockStoreMockRecorder) GetAccountTypeByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountTypeByName", reflect.TypeOf((*MockStore)(nil).GetAccountTypeByName), ctx, name)
}

// ListAccountTypes mocks base method.
func (m *MockStore) ListAccountTypes(ctx context.Context) ([]db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountTypes", ctx)
	ret0, _ := ret[0].([]db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccountTypes indicates an expected call of ListAccountTypes.
func (mr *MockStoreMockRecorder) ListAccountTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountTypes", reflect.TypeOf((*MockStore)(nil).ListAccountTypes), ctx)
}

// UpdateAccountTypeByID mocks base method.
func (m *MockStore) UpdateAccountTypeByID(ctx context.Context, arg db.UpdateAccountTypeByIDParams) (db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountTypeByID", ctx, arg)
	ret0, _ := ret[0].(db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccountTypeByID indicates an expected call of UpdateAccountTypeByID.
func (mr *MockStoreMockRecorder) UpdateAccountTypeByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountTypeByID", reflect.TypeOf((*MockStore)(nil).UpdateAccountTypeByID), ctx, arg)
}
