// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/database/sqlc/ (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen ./internal/database/sqlc/ Querier
//

// Package mock_db is a generated GoMock package.
package mock_db

import (
	context "context"
	reflect "reflect"

	db "github.com/Edu58/Oplan/internal/database/sqlc"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CreateAccountType mocks base method.
func (m *MockQuerier) CreateAccountType(ctx context.Context, arg db.CreateAccountTypeParams) (*db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccountType", ctx, arg)
	ret0, _ := ret[0].(*db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccountType indicates an expected call of CreateAccountType.
func (mr *MockQuerierMockRecorder) CreateAccountType(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccountType", reflect.TypeOf((*MockQuerier)(nil).CreateAccountType), ctx, arg)
}

// DeleteAccountType mocks base method.
func (m *MockQuerier) DeleteAccountType(ctx context.Context, id pgtype.UUID) (*db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccountType", ctx, id)
	ret0, _ := ret[0].(*db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccountType indicates an expected call of DeleteAccountType.
func (mr *MockQuerierMockRecorder) DeleteAccountType(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccountType", reflect.TypeOf((*MockQuerier)(nil).DeleteAccountType), ctx, id)
}

// GetAccountTypeById mocks base method.
func (m *MockQuerier) GetAccountTypeById(ctx context.Context, id pgtype.UUID) (*db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountTypeById", ctx, id)
	ret0, _ := ret[0].(*db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountTypeById indicates an expected call of GetAccountTypeById.
func (mr *MockQuerierMockRecorder) GetAccountTypeById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountTypeById", reflect.TypeOf((*MockQuerier)(nil).GetAccountTypeById), ctx, id)
}

// GetAccountTypeByName mocks base method.
func (m *MockQuerier) GetAccountTypeByName(ctx context.Context, name string) (*db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountTypeByName", ctx, name)
	ret0, _ := ret[0].(*db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountTypeByName indicates an expected call of GetAccountTypeByName.
func (mr *MockQuerierMockRecorder) GetAccountTypeByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountTypeByName", reflect.TypeOf((*MockQuerier)(nil).GetAccountTypeByName), ctx, name)
}

// ListAccountTypes mocks base method.
func (m *MockQuerier) ListAccountTypes(ctx context.Context) ([]*db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountTypes", ctx)
	ret0, _ := ret[0].([]*db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccountTypes indicates an expected call of ListAccountTypes.
func (mr *MockQuerierMockRecorder) ListAccountTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountTypes", reflect.TypeOf((*MockQuerier)(nil).ListAccountTypes), ctx)
}

// UpdateAccountTypeByID mocks base method.
func (m *MockQuerier) UpdateAccountTypeByID(ctx context.Context, arg db.UpdateAccountTypeByIDParams) (*db.AccountType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountTypeByID", ctx, arg)
	ret0, _ := ret[0].(*db.AccountType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccountTypeByID indicates an expected call of UpdateAccountTypeByID.
func (mr *MockQuerierMockRecorder) UpdateAccountTypeByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountTypeByID", reflect.TypeOf((*MockQuerier)(nil).UpdateAccountTypeByID), ctx, arg)
}
